// Generates 15-language content for the SoulPlan event emails and writes
// supabase/functions/soulplan-event-email/content.ts.
//
// Usage: DEEPSEEK_API_KEY=sk-... node scripts/gen_soulplan_emails.mjs
//
// English is the source of truth; the 14 other languages are translated with
// DeepSeek (same approach as the app's tool/translate_arb.dart). Re-run to
// refresh after editing the English copy below.

import fs from "node:fs";

const API = "https://api.deepseek.com/v1/chat/completions";
const KEY = process.env.DEEPSEEK_API_KEY;
if (!KEY) {
  console.error("❌ DEEPSEEK_API_KEY not set");
  process.exit(1);
}

// Tags = the app's canonical BCP-47 base languages (match check-new-users).
const LANGS = {
  es: "Spanish (Spain)", fr: "French (France)", pt: "Portuguese (Brazil)",
  de: "German", it: "Italian", pl: "Polish", tr: "Turkish",
  ar: "Arabic (Modern Standard)", ru: "Russian", hi: "Hindi",
  id: "Indonesian", ja: "Japanese", ko: "Korean", zh: "Simplified Chinese",
};

// English source. Keep the warm, Hooked tone: name the moment, one clear action.
const SOURCE = {
  date_request: {
    subject: "{partner} wants to plan a date with you 💛",
    preheader: "One tap to see the idea they picked for you two.",
    heading: "You've got a date request",
    body: [
      "{partner} just opened SoulPlan and started planning something for the two of you. It's waiting for you now — you only need to take a look and say yes.",
      "The longer it sits, the colder the spark gets. Open it while the excitement is fresh and turn tonight into something you'll both remember.",
    ],
    cta: "See your date",
  },
  date_confirmed: {
    subject: "It's official — your date is set for {time} 💛",
    preheader: "Everything's locked in. Here's how to make it unforgettable.",
    heading: "Your date is confirmed",
    body: [
      "You and {partner} are on for {time}. The hardest part — actually deciding — is done. Now it's just the two of you and a night to look forward to.",
      "Open SoulPlan to start the guided experience when the time comes: the little steps, the conversation prompts, and a place to save the memory afterward.",
    ],
    cta: "View the plan",
  },
};

async function translate(obj, langName) {
  const prompt =
    `Translate the values of this JSON into ${langName} for a warm couples ` +
    `dating app. Keep placeholders like {partner} and {time} EXACTLY as-is. ` +
    `Keep it natural and emotionally warm, not literal. Return ONLY valid JSON ` +
    `with the same keys/shape (arrays stay arrays).\n\n${JSON.stringify(obj)}`;
  const res = await fetch(API, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${KEY}` },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.3,
    }),
  });
  const json = await res.json();
  let c = json.choices[0].message.content.trim()
    .replace(/^```(json)?/i, "").replace(/```$/, "").trim();
  const s = c.indexOf("{"), e = c.lastIndexOf("}");
  return JSON.parse(c.slice(s, e + 1));
}

const out = {};
for (const kind of Object.keys(SOURCE)) {
  out[kind] = { en: SOURCE[kind] };
}
for (const [tag, name] of Object.entries(LANGS)) {
  for (const kind of Object.keys(SOURCE)) {
    process.stdout.write(`\r🌐 ${kind} → ${tag}            `);
    try {
      out[kind][tag] = await translate(SOURCE[kind], name);
    } catch (e) {
      console.error(`\n⚠️ ${kind}/${tag} failed (${e.message}); using English`);
      out[kind][tag] = SOURCE[kind];
    }
  }
}

const banner =
  "// AUTO-GENERATED by scripts/gen_soulplan_emails.mjs — do not edit by hand.\n" +
  "// Edit the English SOURCE in the generator and re-run to refresh.\n";
const ts =
  banner +
  "export type EmailContent = { subject: string; preheader: string; heading: string; body: string[]; cta: string };\n" +
  "export const CONTENT: Record<string, Record<string, EmailContent>> = " +
  JSON.stringify(out, null, 2) + ";\n";

const dir = "supabase/functions/soulplan-event-email";
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(`${dir}/content.ts`, ts);
console.log(`\n✨ Wrote ${dir}/content.ts (${Object.keys(LANGS).length + 1} langs)`);
