// AUTO-GENERATED by scripts/gen_soulplan_emails.mjs — do not edit by hand.
// Edit the English SOURCE in the generator and re-run to refresh.
export type EmailContent = { subject: string; preheader: string; heading: string; body: string[]; cta: string };
export const CONTENT: Record<string, Record<string, EmailContent>> = {
  "date_request": {
    "en": {
      "subject": "{partner} wants to plan a date with you 💛",
      "preheader": "One tap to see the idea they picked for you two.",
      "heading": "You've got a date request",
      "body": [
        "{partner} just opened SoulPlan and started planning something for the two of you. It's waiting for you now — you only need to take a look and say yes.",
        "The longer it sits, the colder the spark gets. Open it while the excitement is fresh and turn tonight into something you'll both remember."
      ],
      "cta": "See your date"
    },
    "es": {
      "subject": "{partner} quiere planear una cita contigo 💛",
      "preheader": "Un toque para ver la idea que han elegido para vosotros dos.",
      "heading": "Tienes una invitación de cita",
      "body": [
        "{partner} acaba de abrir SoulPlan y ha empezado a preparar algo especial para vosotros dos. Ya te está esperando — solo tienes que echarle un vistazo y decir que sí.",
        "Cuanto más tiempo pase, más se enfría la chispa. Ábrelo mientras la emoción está fresca y convertid esta noche en algo que recordaréis los dos."
      ],
      "cta": "Ver tu cita"
    },
    "fr": {
      "subject": "{partner} veut organiser un rendez-vous avec toi 💛",
      "preheader": "Un clic pour découvrir l’idée qu’ils ont choisie pour vous deux.",
      "heading": "Tu as une demande de rendez-vous",
      "body": [
        "{partner} vient d’ouvrir SoulPlan et a commencé à préparer quelque chose pour vous deux. Ça t’attend — il te suffit de jeter un œil et de dire oui.",
        "Plus tu attends, plus la magie s’estompe. Ouvre-le tant que l’excitation est là et fais de ce soir un souvenir inoubliable à deux."
      ],
      "cta": "Voir ton rendez-vous"
    },
    "pt": {
      "subject": "{partner} quer planejar um encontro com você 💛",
      "preheader": "Um toque para ver a ideia que ele(a) escolheu para vocês dois.",
      "heading": "Você recebeu um convite de encontro",
      "body": [
        "{partner} acabou de abrir o SoulPlan e começou a planejar algo especial para vocês dois. Já está te esperando — é só dar uma olhada e aceitar.",
        "Quanto mais tempo passa, mais a magia se desfaz. Abra enquanto a empolgação está no ar e transforme esta noite em algo que vocês vão lembrar para sempre."
      ],
      "cta": "Ver seu encontro"
    },
    "de": {
      "subject": "{partner} möchte ein Date mit dir planen 💛",
      "preheader": "Ein Klick und du siehst, welche Idee {partner} für euch beide ausgesucht hat.",
      "heading": "Du hast eine Date-Anfrage",
      "body": [
        "{partner} hat gerade SoulPlan geöffnet und angefangen, etwas für euch beide zu planen. Es wartet schon auf dich – du musst nur einen Blick darauf werfen und Ja sagen.",
        "Je länger es liegen bleibt, desto mehr verfliegt die Aufregung. Schau es dir an, solange die Vorfreude noch frisch ist, und macht aus diesem Abend etwas, an das ihr beide noch lange denkt."
      ],
      "cta": "Date ansehen"
    },
    "it": {
      "subject": "{partner} vuole organizzare un appuntamento con te 💛",
      "preheader": "Un tocco per vedere l'idea che hanno scelto per voi due.",
      "heading": "Hai ricevuto una richiesta di appuntamento",
      "body": [
        "{partner} ha appena aperto SoulPlan e ha iniziato a organizzare qualcosa per voi due. Ti sta aspettando — basta dare un'occhiata e dire di sì.",
        "Più tempo passa, più la scintilla si raffredda. Apri l'invito mentre l'entusiasmo è ancora vivo e trasforma questa serata in un ricordo che porterete nel cuore."
      ],
      "cta": "Scopri il tuo appuntamento"
    },
    "pl": {
      "subject": "{partner} chce zaplanować z Tobą randkę 💛",
      "preheader": "Jedno kliknięcie, by zobaczyć pomysł, który dla Was wybrał.",
      "heading": "Masz propozycję randki",
      "body": [
        "{partner} właśnie otworzył SoulPlan i zaczął planować coś dla Was dwojga. Czeka już na Ciebie — wystarczy, że rzucisz okiem i powiesz „tak”.",
        "Im dłużej to odkładasz, tym bardziej gaśnie iskra. Otwórz, póki emocje są świeże, i zamień ten wieczór w coś, co oboje zapamiętacie."
      ],
      "cta": "Zobacz swoją randkę"
    },
    "tr": {
      "subject": "{partner} seninle bir randevu planlamak istiyor 💛",
      "preheader": "Sizin için seçtiği fikri görmek için tek bir dokunuş yeterli.",
      "heading": "Bir randevu teklifin var",
      "body": [
        "{partner} az önce SoulPlan'ı açtı ve ikiniz için bir şeyler planlamaya başladı. Şimdi seni bekliyor — sadece bir bakıp onaylaman yeterli.",
        "Ne kadar bekletirsen, o kıvılcım o kadar soğur. Heyecan tazeyken aç ve bu geceyi ikinizin de hatırlayacağı bir ana dönüştür."
      ],
      "cta": "Randevunu gör"
    },
    "ar": {
      "subject": "{partner} يريد التخطيط لموعد معك 💛",
      "preheader": "اضغط مرة واحدة لترى الفكرة التي اختارها لكما.",
      "heading": "لديك طلب موعد",
      "body": [
        "{partner} فتح للتو SoulPlan وبدأ في التخطيط لشيء لكما. إنه في انتظارك الآن — كل ما عليك هو إلقاء نظرة والموافقة.",
        "كلما طال الانتظار، كلما خفت الشرارة. افتحه بينما الحماس طازج وحوّل هذه الليلة إلى شيء ستتذكرانه معًا."
      ],
      "cta": "شاهد موعدك"
    },
    "ru": {
      "subject": "{partner} хочет запланировать свидание с тобой 💛",
      "preheader": "Один тап — и ты увидишь идею, которую они выбрали для вас двоих.",
      "heading": "Тебе пришёл запрос на свидание",
      "body": [
        "{partner} только что открыл(а) SoulPlan и начал(а) планировать что-то для вас двоих. Оно уже ждёт тебя — нужно лишь взглянуть и сказать «да».",
        "Чем дольше оно лежит, тем слабее искра. Открой, пока волнение свежо, и преврати этот вечер в то, что вы оба запомните."
      ],
      "cta": "Посмотреть свидание"
    },
    "hi": {
      "subject": "{partner} आपके साथ डेट प्लान करना चाहता है 💛",
      "preheader": "एक टैप करके देखें उन्होंने आप दोनों के लिए क्या सोचा है।",
      "heading": "आपके लिए एक डेट रिक्वेस्ट आई है",
      "body": [
        "{partner} ने अभी-अभी SoulPlan खोला और आप दोनों के लिए कुछ प्लान करना शुरू किया है। यह आपका इंतज़ार कर रहा है — बस एक नज़र डालें और हाँ कहें।",
        "जितनी देर यह पड़ा रहेगा, उतनी ही ठंडी पड़ती जाएगी चमक। इसे तब खोलें जब उत्साह ताज़ा हो और आज की रात को कुछ यादगार बनाएं।"
      ],
      "cta": "अपनी डेट देखें"
    },
    "id": {
      "subject": "{partner} ingin merencanakan kencan denganmu 💛",
      "preheader": "Satu ketukan untuk melihat ide yang mereka pilih untuk kalian berdua.",
      "heading": "Kamu dapat permintaan kencan",
      "body": [
        "{partner} baru saja membuka SoulPlan dan mulai merencanakan sesuatu untuk kalian berdua. Ini sudah menunggumu — kamu hanya perlu melihat dan mengiyakan.",
        "Semakin lama didiamkan, semakin dingin percikannya. Buka selagi semangat masih hangat, dan jadikan malam ini sesuatu yang akan kalian kenang bersama."
      ],
      "cta": "Lihat kencanmu"
    },
    "ja": {
      "subject": "{partner}があなたとのデートを計画したいみたい💛",
      "preheader": "タップひとつで、2人のために選んでくれたアイデアが見えるよ。",
      "heading": "デートのお誘いが届いています",
      "body": [
        "{partner}がSoulPlanを開いて、2人のための何かを計画し始めたよ。もうあなたの返事を待っている——見て、うなずくだけで大丈夫。",
        "長く置いておくほど、ときめきは冷めていくもの。そのワクワクが新鮮なうちに開いて、今夜を2人だけの思い出にしよう。"
      ],
      "cta": "デートをチェックする"
    },
    "ko": {
      "subject": "{partner}님이 당신과의 데이트를 계획하고 싶어 해요 💛",
      "preheader": "탭 한 번으로 그들이 골라준 아이디어를 확인해 보세요.",
      "heading": "데이트 신청이 도착했어요",
      "body": [
        "{partner}님이 방금 SoulPlan을 열고 둘만의 시간을 준비하기 시작했어요. 지금 당신의 답변을 기다리고 있어요 — 확인하고 '좋아요'만 하면 돼요.",
        "오래 기다릴수록 설렘도 식기 마련이에요. 지금 이 기분이 식기 전에 열어보고, 오늘 밤을 잊지 못할 추억으로 만들어 보세요."
      ],
      "cta": "데이트 확인하기"
    },
    "zh": {
      "subject": "{partner} 想和你一起计划一次约会 💛",
      "preheader": "点一下就能看到TA为你俩挑选的约会点子。",
      "heading": "你收到了一条约会邀请",
      "body": [
        "{partner} 刚刚打开 SoulPlan，开始为你们俩策划点什么。现在正等着你呢——你只需要看一眼，然后说声“好”。",
        "放得越久，火花就越容易变凉。趁这份心动还热乎着，点开它，把今晚变成你们都会记住的回忆。"
      ],
      "cta": "查看你的约会"
    }
  },
  "date_confirmed": {
    "en": {
      "subject": "It's official — your date is set for {time} 💛",
      "preheader": "Everything's locked in. Here's how to make it unforgettable.",
      "heading": "Your date is confirmed",
      "body": [
        "You and {partner} are on for {time}. The hardest part — actually deciding — is done. Now it's just the two of you and a night to look forward to.",
        "Open SoulPlan to start the guided experience when the time comes: the little steps, the conversation prompts, and a place to save the memory afterward."
      ],
      "cta": "View the plan"
    },
    "es": {
      "subject": "Es oficial — tu cita está confirmada para {time} 💛",
      "preheader": "Todo está listo. Aquí tienes cómo hacer que sea inolvidable.",
      "heading": "Tu cita está confirmada",
      "body": [
        "Tú y {partner} os veis el {time}. Lo más difícil — decidirlo — ya está hecho. Ahora solo quedáis vosotros dos y una noche que esperar con ilusión.",
        "Abre SoulPlan cuando llegue el momento para empezar la experiencia guiada: los pequeños pasos, las ideas para conversar y un lugar donde guardar el recuerdo después."
      ],
      "cta": "Ver el plan"
    },
    "fr": {
      "subject": "C'est officiel — votre rendez-vous est fixé à {time} 💛",
      "preheader": "Tout est calé. Voici comment le rendre inoubliable.",
      "heading": "Votre rendez-vous est confirmé",
      "body": [
        "Vous et {partner} êtes programmé·e·s pour {time}. La partie la plus difficile — décider — est derrière vous. Il ne reste plus que vous deux et une soirée à attendre avec impatience.",
        "Ouvrez SoulPlan pour lancer l'expérience guidée le moment venu : les petites étapes, les suggestions de conversation, et un endroit pour garder le souvenir après."
      ],
      "cta": "Voir le plan"
    },
    "pt": {
      "subject": "Tá oficial — seu encontro está marcado para {time} 💛",
      "preheader": "Tudo certo por aqui. Veja como tornar esse momento inesquecível.",
      "heading": "Seu encontro está confirmado",
      "body": [
        "Você e {partner} estão com tudo marcado para {time}. A parte mais difícil — decidir — já passou. Agora é só vocês dois e uma noite para esperar com carinho.",
        "Abra o SoulPlan quando chegar a hora: passos simples, sugestões de conversa e um lugar para guardar essa memória depois."
      ],
      "cta": "Ver o plano"
    },
    "de": {
      "subject": "Es ist offiziell — euer Date steht für {time} 💛",
      "preheader": "Alles ist fix. So wird es unvergesslich.",
      "heading": "Euer Date ist bestätigt",
      "body": [
        "Du und {partner} seid für {time} verabredet. Der schwerste Teil — die Entscheidung — ist geschafft. Jetzt seid nur ihr zwei und ein Abend, auf den ihr euch freuen könnt.",
        "Öffne SoulPlan, wenn es so weit ist, um die geführte Erfahrung zu starten: die kleinen Schritte, die Gesprächsanregungen und einen Ort, um die Erinnerung danach festzuhalten."
      ],
      "cta": "Plan ansehen"
    },
    "it": {
      "subject": "È ufficiale — il tuo appuntamento è fissato per {time} 💛",
      "preheader": "Tutto è confermato. Ecco come renderlo indimenticabile.",
      "heading": "Il tuo appuntamento è confermato",
      "body": [
        "Tu e {partner} siete in programma per {time}. La parte più difficile — decidere, appunto — è fatta. Ora ci siete solo voi due e una serata da attendere con gioia.",
        "Apri SoulPlan per iniziare l'esperienza guidata quando arriva il momento: i piccoli passi, gli spunti di conversazione e un posto dove conservare il ricordo dopo."
      ],
      "cta": "Vedi il piano"
    },
    "pl": {
      "subject": "To oficjalne — wasza randka zaplanowana na {time} 💛",
      "preheader": "Wszystko dopięte na ostatni guzik. Oto jak sprawić, by było niezapomniane.",
      "heading": "Wasza randka potwierdzona",
      "body": [
        "Ty i {partner} macie randkę o {time}. Najtrudniejsza część — samo zdecydowanie — już za wami. Teraz tylko wy dwoje i wieczór, na który warto czekać.",
        "Otwórzcie SoulPlan, gdy nadejdzie czas, by rozpocząć prowadzone doświadczenie: małe kroki, podpowiedzi do rozmów i miejsce, by zachować wspomnienie na później."
      ],
      "cta": "Zobacz plan"
    },
    "tr": {
      "subject": "Resmi — randevun {time} için ayarlandı 💛",
      "preheader": "Her şey hazır. İşte bu anı unutulmaz kılmanın yolları.",
      "heading": "Randevun onaylandı",
      "body": [
        "Sen ve {partner}, {time} için buluşuyorsunuz. En zor kısım — karar vermek — bitti. Şimdi sadece ikiniz ve dört gözle bekleyeceğiniz bir gece kaldı.",
        "Zamanı gelince SoulPlan’ı açarak rehberli deneyimi başlatın: küçük adımlar, sohbet başlatıcıları ve sonrasında anıyı kaydedebileceğiniz bir yer."
      ],
      "cta": "Planı görüntüle"
    },
    "ar": {
      "subject": "أصبح الأمر رسميًا — موعدكما محدد في {time} 💛",
      "preheader": "كل شيء مؤكد. إليك كيف تجعله لا يُنسى.",
      "heading": "تم تأكيد موعدكما",
      "body": [
        "أنت و{partner} على موعد في {time}. الجزء الأصعب — وهو اتخاذ القرار — قد انتهى. الآن الأمر فقط بينكما وليلة تنتظرانها.",
        "افتح SoulPlan لبدء التجربة المُوجَّهة عندما يحين الوقت: الخطوات الصغيرة، وأسئلة المحادثة، ومكان لحفظ الذكرى بعد ذلك."
      ],
      "cta": "عرض الخطة"
    },
    "ru": {
      "subject": "Всё официально — ваше свидание назначено на {time} 💛",
      "preheader": "Всё готово. Вот как сделать этот вечер незабываемым.",
      "heading": "Ваше свидание подтверждено",
      "body": [
        "Вы и {partner} встречаетесь {time}. Самое сложное — решиться — уже позади. Теперь остались только вы двое и вечер, которого стоит ждать.",
        "Откройте SoulPlan, когда придёт время, чтобы начать guided-опыт: маленькие шаги, подсказки для разговора и место, где можно сохранить воспоминания после."
      ],
      "cta": "Посмотреть план"
    },
    "hi": {
      "subject": "यह आधिकारिक है — आपकी डेट {time} के लिए तय हो गई है 💛",
      "preheader": "सब कुछ पक्का है। इसे अविस्मरणीय बनाने के तरीके यहाँ हैं।",
      "heading": "आपकी डेट कन्फर्म है",
      "body": [
        "आप और {partner} {time} पर मिल रहे हैं। सबसे मुश्किल काम — फैसला करना — अब हो चुका है। अब बस आप दोनों हैं और एक शाम जिसका इंतज़ार करना है।",
        "जब समय आए, तो SoulPlan खोलें और गाइडेड अनुभव शुरू करें: छोटे-छोटे कदम, बातचीत के संकेत, और बाद में यादों को संजोने की जगह।"
      ],
      "cta": "प्लान देखें"
    },
    "id": {
      "subject": "Resmi ya — kencan kalian sudah dijadwalkan untuk {time} 💛",
      "preheader": "Semuanya sudah pasti. Ini cara membuatnya tak terlupakan.",
      "heading": "Kencanmu sudah dikonfirmasi",
      "body": [
        "Kamu dan {partner} sudah janjian untuk {time}. Bagian tersulit — memutuskan — sudah selesai. Sekarang tinggal kalian berdua dan malam yang bisa dinantikan.",
        "Buka SoulPlan untuk memulai pengalaman terpandu saat waktunya tiba: langkah-langkah kecil, topik obrolan, dan tempat untuk menyimpan kenangan setelahnya."
      ],
      "cta": "Lihat rencana"
    },
    "ja": {
      "subject": "正式決定 — {partner}とのデートは{time}に決まりました 💛",
      "preheader": "準備は万端。忘れられない夜にするためのヒントをお届けします。",
      "heading": "デートが確定しました",
      "body": [
        "{partner}と{time}にお出かけですね。一番大変だった「決める」が終わったら、あとはふたりで楽しむだけ。素敵な夜を心待ちにしていてください。",
        "当日はSoulPlanを開いて、ガイド付きの体験を始めてみてください：小さなステップ、会話のきっかけ、そして後で思い出を保存できる場所もあります。"
      ],
      "cta": "プランを見る"
    },
    "ko": {
      "subject": "공식 확정 — {partner}님과의 데이트가 {time}에 잡혔어요 💛",
      "preheader": "모든 준비 완료. 잊지 못할 순간을 만드는 방법을 알려드릴게요.",
      "heading": "데이트가 확정되었어요",
      "body": [
        "{partner}님과 {time}에 만나기로 했네요. 가장 어려운 결정은 끝났어요. 이제 둘이서 기대되는 밤을 기다리기만 하면 돼요.",
        "시간이 되면 SoulPlan을 열어 가이드를 따라가보세요: 작은 단계들, 대화를 도와주는 질문들, 그리고 나중에 추억을 저장할 공간까지 준비되어 있어요."
      ],
      "cta": "플랜 보기"
    },
    "zh": {
      "subject": "正式确认啦——你和{partner}的约会定在{time}啦 💛",
      "preheader": "一切就绪。来看看怎样让这次约会难忘吧。",
      "heading": "约会已确认",
      "body": [
        "你和{partner}约好了在{time}见面。最难的部分——做决定——已经搞定啦。接下来就只剩你们俩，一起期待这个美好的夜晚。",
        "到时候打开SoulPlan，跟着指引一步步来：小提示、聊天话题，还有事后保存回忆的地方。"
      ],
      "cta": "查看计划"
    }
  }
};
